# deb.mk

DEB_TARGETS = deb deb-tmp deb-clean

DEB_ARCHITECTURE=$(shell dpkg-architecture -q'DEB_BUILD_ARCH')

$(TMPDIR)/DEBUILD/$(PACKAGE_NAME)-$(PACKAGE_FULL_VERSION).tar.gz: $(PACKAGE_NAME)-$(PACKAGE_FULL_VERSION).tar.gz
	@$(CP) $? $@

$(TMPDIR)/DEBUILD/$(PACKAGE_NAME)-$(PACKAGE_FULL_VERSION): $(TMPDIR)/DEBUILD/$(PACKAGE_NAME)-$(PACKAGE_FULL_VERSION).tar.gz
	@$(TAR) -C $(TMPDIR)/DEBUILD -xf $?

$(TMPDIR)/DEBUILD/$(PACKAGE_NAME)_$(PACKAGE_FULL_VERSION)_$(DEB_ARCHITECTURE).deb: $(TMPDIR)/DEBUILD/$(PACKAGE_NAME)-$(PACKAGE_FULL_VERSION)
	@$(ECHO) "   DEB $(PACKAGE_NAME)_$(PACKAGE_FULL_VERSION)_$(DEB_ARCHITECTURE).deb"
	@cd $? && debuild -i -us -uc -b > /dev/null 2>&1

$(PACKAGE_NAME)_$(PACKAGE_FULL_VERSION)_$(DEB_ARCHITECTURE).deb: $(TMPDIR)/DEBUILD/$(PACKAGE_NAME)_$(PACKAGE_FULL_VERSION)_$(DEB_ARCHITECTURE).deb
	@$(CP) $? $@

deb: deb-tmp $(PACKAGE_NAME)_$(PACKAGE_FULL_VERSION)_$(DEB_ARCHITECTURE).deb

deb-tmp: | $(TMPDIR)/DEBUILD

deb-clean:
	@$(ECHO) "    RM $(PACKAGE_NAME)-$(PACKAGE_FULL_VERSION)_$(DEB_ARCHITECTURE).deb"
	@$(RM) $(TMPDIR)/DEBUILD $(PACKAGE_NAME)_$(PACKAGE_FULL_VERSION)_$(DEB_ARCHITECTURE).deb
